// Code generated by protoc-gen-go.
// source: mood.proto
// DO NOT EDIT!

/*
Package moodometer is a generated protocol buffer package.

It is generated from these files:
	mood.proto

It has these top-level messages:
	User
	Mood
	Meter
	Moods
*/
package moodometer

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type User struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Moods *Moods `protobuf:"bytes,3,opt,name=moods" json:"moods,omitempty"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetMoods() *Moods {
	if m != nil {
		return m.Moods
	}
	return nil
}

type Mood struct {
	Mind   string `protobuf:"bytes,1,opt,name=mind" json:"mind,omitempty"`
	Score  int32  `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	Smiley string `protobuf:"bytes,3,opt,name=smiley" json:"smiley,omitempty"`
	Date   int32  `protobuf:"varint,4,opt,name=date" json:"date,omitempty"`
	User   *User  `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
}

func (m *Mood) Reset()         { *m = Mood{} }
func (m *Mood) String() string { return proto.CompactTextString(m) }
func (*Mood) ProtoMessage()    {}

func (m *Mood) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Meter struct {
	Avg     float32  `protobuf:"fixed32,1,opt,name=avg" json:"avg,omitempty"`
	XSmiley []string `protobuf:"bytes,2,rep,name=xSmiley" json:"xSmiley,omitempty"`
}

func (m *Meter) Reset()         { *m = Meter{} }
func (m *Meter) String() string { return proto.CompactTextString(m) }
func (*Meter) ProtoMessage()    {}

type Moods struct {
	Moods []*Mood `protobuf:"bytes,1,rep,name=moods" json:"moods,omitempty"`
}

func (m *Moods) Reset()         { *m = Moods{} }
func (m *Moods) String() string { return proto.CompactTextString(m) }
func (*Moods) ProtoMessage()    {}

func (m *Moods) GetMoods() []*Mood {
	if m != nil {
		return m.Moods
	}
	return nil
}

func init() {
}
